../../../node_modules/less/bin/lessc --js -x ./default.less ../dist/default.css
../../../node_modules/less/bin/lessc --js -x ./cyan.less ../dist/cyan.css
../../../node_modules/less/bin/lessc --js -x ./geek-blue.less ../dist/geek-blue.css
../../../node_modules/less/bin/lessc --js -x ./gold.less ../dist/gold.css
../../../node_modules/less/bin/lessc --js -x ./lime.less ../dist/lime.css
../../../node_modules/less/bin/lessc --js -x ./magenta.less ../dist/magenta.css
../../../node_modules/less/bin/lessc --js -x ./orange.less ../dist/orange.css
../../../node_modules/less/bin/lessc --js -x ./polar-green.less ../dist/polar-green.css
../../../node_modules/less/bin/lessc --js -x ./purple.less ../dist/purple.css
../../../node_modules/less/bin/lessc --js -x ./red.less ../dist/red.css
../../../node_modules/less/bin/lessc --js -x ./volcano.less ../dist/volcano.css
../../../node_modules/less/bin/lessc --js -x ./yellow.less ../dist/yellow.css